using System;
using System.Collections.Generic;

namespace BloonsTD5Rewritten.Godot.Scripts.Towers;

[Flags]
public enum TowerType : ulong
{
    Invalid = 0,
    TestTower = 1 << 0,
    DartMonkey = 1 << 1,
    TackTower = 1 << 2,
    SniperMonkey = 1 << 3,
    BoomerangThrower = 1 << 4,
    NinjaMonkey = 1 << 5,
    BombTower = 1 << 6,
    IceTower = 1 << 7,
    GlueGunner = 1 << 8,
    MonkeyBuccaneer = 1 << 9,
    MonkeyAce = 1 << 10,
    SuperMonkey = 1 << 11,
    MonkeyApprentice = 1 << 12,
    MonkeyVillage = 1 << 13,
    BananaFarm = 1 << 14,
    MortarTower = 1 << 15,
    DartlingGun = 1 << 16,
    SpikeFactory = 1 << 17,
    HeliPilot = 1 << 18,
    RoadSpikes = 1 << 19,
    ExplodingPineapple = 1 << 20,
    MonkeyEngineer = 1 << 21,
    Bloonchipper = 1 << 22,
    MonkeySub = 1 << 23,
    MeerkatSpyPro = 1 << 24,
    MeerkatSpy = 1 << 25,
    TribalTurtlePro = 1 << 26,
    TribalTurtle = 1 << 27,
    PortableLakePro = 1 << 28,
    PortableLake = 1 << 29,
    PontoonPro = 1 << 30,
    Pontoon = 1UL << 31,
    BloonsdayDevicePro = 1UL << 32,
    BloonsdayDevice = 1UL << 33,
    AngrySquirrelPro = 1UL << 34,
    AngrySquirrel = 1UL << 35,
    SuperMonkeyStormPro = 1UL << 36,
    SuperMonkeyStorm = 1UL << 37,
    BeeKeeperPro = 1UL << 38,
    BeeKeeper = 1UL << 39,
    BloonberryBushPro = 1UL << 40,
    BloonberryBush = 1UL << 41,
    RadadactylPro = 1UL << 42,
    Radadactyl = 1UL << 43,
    BananaFarmerPro = 1UL << 44,
    BananaFarmer = 1UL << 45,
    NinjaKiwiPro = 1UL << 46,
    NinjaKiwi = 1UL << 47,
    WizardLord = 1UL << 48,
    AcePlane = 1UL << 49,
    AircraftCarrier = 1UL << 50,
    PhoenixPlane = 1UL << 51,
    SuperPhoenixPlane = 1UL << 52,
    SupplyDropPlane = 1UL << 53,
    HeliPilotAircraft = 1UL << 54,
    RadadactylPlane = 1UL << 55,
    RadderdactylPlane = 1UL << 56,
    MonkeyEngineerSentry = 1UL << 57,
    MonkeyEngineerSentryTier4 = 1UL << 58,
    GameDummy = 1UL << 59
}